name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  call-release-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.9.0
    with:
      release_prefix: ZRAN
      release_branch: main      # Optional; default shown
      develop_branch: develop   # Optional; default shown
      sync_pr_label: zran-bot  # Optional; default shown
    secrets:
      USER_TOKEN: ${{ secrets.ZRAN_BOT_PAK }}
